server {
    listen 9000;
    server_name localhost 127.0.0.1 host.docker.internal;

    root /var/www/www-data/netcinema.loc/public;

    index index.php;

    access_log /var/log/nginx/netcinema.access.log main;
    error_log /var/log/nginx/netcinema.error.log warn;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    include /etc/nginx/common.conf;
}
